# Generated by Django 3.2.15 on 2022-09-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Snacks', 'Snacks'), ('Meals', 'Meals'), ('Desserts', 'Desserts')], default='Snacks', max_length=8),
        ),
    ]
